[package]
name = "example-userspace"
version = "0.1.0"
authors = ["Junyeong Jeong <rhdxmr@gmail.com>"]
edition = "2018"

[build-dependencies]
cargo-bpf = { version = "", path = "../../cargo-bpf", default-features = false, features = ["build"] }

[dependencies]
probes = { path = "../example-probes", package = "example-probes" }
libc = "0.2"
tokio = { version = "1.2", features = ["signal", "time"] }
redbpf = { version = "", path = "../../redbpf", features = ["load"] }
futures = "0.3"
